### ISSUE TITLE
Can't manually type in a nested url

### ISSUE THREAD

**Issue by ghost** [firebase/firebase-angular-starter-pack#20]
This is my main concern for using firebase. Most SPA's use a custom backend which has a catchall route handler that allows this feature (gmail, youtube, etc), but with firebase users have to start from the root path before navigating the routes. This issue may be out of scope since I'm guessing it's not possible with firebase, but is there something I can add to make this work? Thanks.

**Comment by abehaskins** [comment]
You can definitely do this with [Firebase Hosting](https://firebase.google.com/docs/hosting/) and actually when you use the `firebase` CLI it will ask if you'd like to configure your paths to work as a typical SPA does (as you describe!) So I'd look into that :)
