### ISSUE TITLE
This repo is extremely out of date.

### ISSUE THREAD

**Issue by nikmartin** [firebase/firebase-angular-starter-pack#21]
Just an FYI, for new firebase users trying to get up to speed on Firebase, the preponderance of docs and projects that are very old and out of date is a bit disconcerting. This project uses 1.2.7  of the firebase libs, so they really are nit usable anymore. You might consider unpublishing them until they can be updated to a new version. That and the fact that every search for 'Firebase" sends you to outdated docs  firebase.com has made the past two days a huge struggle to get up to speed on using firebase.

**Comment by abehaskins** [comment]
I've added a huge notice on the README and we'll be closing Github Issues and disabling this repo in favor of newer samples soon. Thanks for bringing this to my attention!
