### ISSUE TITLE
Update firebase.js and firebase-simple-login.js includes to latest version.

### ISSUE THREAD

**Issue by mikelehen** [firebase/firebase-angular-starter-pack#8]
Friend of mine ran into trouble getting google auth to work, since the seed is referencing an old version of simple login.

**Comment by abehaskins** [comment]
Hey Mike, thanks for reaching out, but we're no longer maintaining this starter pack for new versions of Firebase. Perhaps you could check out the [Web client for FriendlyChat](https://github.com/firebase/friendlychat) to see a more up-to-date auth example.
